### PR TITLE
WIP: Convert to ProjectScaffold

### PR DESCRIPTION
**Pull request by forki**
Please don't merge yet

### CODE REVIEW

**Comment by forki** [comment]
@dungpa any ideas what this error means?

**Comment by hmemcpy** [comment]
I'd much rather you used the [VSSDK packages](https://github.com/tunnelvisionlabs/vsxdeps) instead of adding binaries directly, if you can avoid it.

**Comment by forki** [comment]
alive

it's alive!

**Comment by hmemcpy** [comment]
Nice! I'm merging!

**Comment by forki** [comment]
noooo

**Comment by forki** [comment]
OK. will create new PR to add the additions..

**Comment by hmemcpy** [comment]
Sorry, I'm too exited. I'll wait for your ok next time :)

**Pull request merged**
