### PR TITLE
Start to automate the vsix deployment

### PR DESCRIPTION
**Pull request by forki**
vsix

For the canopy magic see https://github.com/fsprojects/Paket.VisualStudio/compare/deploy?expand=1#diff-6074983490330a0aac1bd23c958232d7R151

This assumes the vsix was already uploaded once.

### CODE REVIEW

**Comment by dungpa** [comment]
Nice approach. However, if you log in from another country, the stupid security questions may f*ck up the login process.

**Comment by forki** [comment]
"Start to automate" ;-)

**Comment by forki** [comment]
@dungpa 
I updated the vsix but it still shows the old version.

image

how gets this changed?

**Comment by dungpa** [comment]
I saw vsixmanifest version is bumped in the PR. It should be fine.
Could you open vsix file as a zip file and check whether vsixmanifest file consists of correct version?

**Comment by forki** [comment]
seems I just need to do additional "Save". now it works.

**Pull request merged**
