### PR TITLE
Changing the vsixmanifest to support VS2017 builds

### PR DESCRIPTION
**Pull request by hmemcpy**
Should be fine now!

### CODE REVIEW

**Comment by hmemcpy** [comment]
This fixes #129

**Comment by forki** [comment]
@hmemcpy very cool. thank you so much.  💋

**Comment by forki** [comment]
ok seems Visual Studio gallery doesn't like that:

image

**Comment by hmemcpy** [comment]
Shit :( I just realized it builds an incompatible vsix :((
I'll investigate asap!

**Comment by forki** [comment]
there might be a small road block right now: https://github.com/Microsoft/visualfsharp/issues/2286 ;-)

**Comment by hmemcpy** [comment]
I added a "hack" to .vsixmanifest file - a `<Prerequisites>` element, so it would compile with 2017. I figured, earlier VSIX would simply ignore this. I was right, it works if executed with VSIXInstaller.exe of VS2015, but the new VSIXInstaller in 2017 thinks the vsix is broken :((
I'll work some more magic!

**Comment by hmemcpy** [comment]
Fixed via #134

**Pull request merged**
