### PR TITLE
Paket.ico added

### PR DESCRIPTION
**Pull request by sergey-tihon**
https://github.com/hmemcpy/Paket.VisualStudio/issues/11

### CODE REVIEW

**Comment by forki** [comment]
question is how can we change the icon for existing node!?

**Comment by sergey-tihon** [comment]
The good question, because I cannot do this...
I tried several ways but they do not work

**Comment by sergey-tihon** [comment]
Maybe @madskristensen knows if possible to change icon or existing node (or not) ;)

**Comment by madskristensen** [comment]
I haven't found a way to do so

**Comment by hmemcpy** [comment]
When you say existing node, which one do you mean? Because I think it's possible to set it via registry, no? @madskristensen

**Comment by hmemcpy** [comment]
Otherwise, there's always private reflection :)

**Comment by forki** [comment]
image

we would like to change this icon. It's the root of the packages.

**Comment by hmemcpy** [comment]
I'm pretty sure it's possible, but honestly, I haven't done it yet. If @madskristensen doesn't know, then I guess it's... Going to be difficult :)

**Pull request merged**
