### PR TITLE
Fixed Intellisense bug with packages that contain a .

### PR DESCRIPTION
**Pull request by forki**
intellisense

### CODE REVIEW

**Comment by hmemcpy** [comment]
Awesome! I refactored this part a bit, but still had that bug.
I actually started using `DependenciesFileParser.parseDependencyLine` to try and figure out where I was... but I didn't get too much done yet :(

**Comment by forki** [comment]
Yeah I cheated a bit and just retrieved the whole line from the buffer. 

Side question: even if the keyword completion gets raised, shouldn't it be filtered?

**Comment by forki** [comment]
I introduced a new bug. :-( trying to fix now

**Comment by forki** [comment]
fixed it. and also implemented:

image

**Pull request merged**
