### PR TITLE
Using MahApps.Metro styles and paradigms

### PR DESCRIPTION
**Pull request by TheAngryByrd**
Version of the UI using MahApps.Metro

paketadduimodern

Gif looks kind of goofy/blurry now that I look at it.  Know of anything better than ScreenToGif?
#37 #38

### CODE REVIEW

**Comment by forki** [comment]
This gets better and better. Cool work

**Comment by forki** [comment]
just tried AddPackage and it failed, but the error got eaten.

image

did you see this before?

**Comment by hmemcpy** [comment]
This is absolutely gorgeous! Well done!

Quick question: do we want to suppress the "modified outside VS" dialog for certain files? Like paket.lock? There shouldn't be a reason it won't be always updated from the outside.

**Comment by forki** [comment]
Yes. Paket.lock, paket.dependencies and paket.references are changed by the tool. I assume paket.references is already ok since we unload the project, but the other 2 should be handled.

**Comment by hmemcpy** [comment]
I'll need to check if NuGet are doing it. What happens if you update a package and you have `packages.config` opened? There's API to suppress that "modified from the outside" message (and always reload), but it's not pretty. Either way, I'll open an issue for it.

**Comment by forki** [comment]
It's not important if NuGet is doing it. We should concentrate on our workflow ;-)

**Comment by hmemcpy** [comment]
Right, but I'm always thinking of where to stea^H^H^H^Hlook at reference
implementation :)

On Tue, May 19, 2015 at 10:43 AM, Steffen Forkmann <notifications@github.com

**Comment by forki** [comment]
that's an excellent reason.

**Comment by TheAngryByrd** [comment]
Nope I didn't get that error but looks like I just need to do more error handling.

**Comment by TheAngryByrd** [comment]
What stage of the process did it crash?  Just opening?

That error sometimes masks another problem :unamused: 
https://github.com/reactiveui/ReactiveUI/blob/8ba2775f1e301e27ee15720d4c3d41fd4ecdd321/ReactiveUI/RxApp.cs#L50-64

**Comment by forki** [comment]
no I think it crashed after the process got finished. I assume paket.core was throwing, but can't say.

**Comment by TheAngryByrd** [comment]
Time to add all the error logging!

**Comment by forki** [comment]
"all the error logging"
"If you liked it, then you shoulda put a try/catch on it" 

beyonce

**Comment by TheAngryByrd** [comment]
How does this ever work? 
exceptionsgalore

**Comment by forki** [comment]
What is that?

**Comment by TheAngryByrd** [comment]
Just the output window when debugging the vsix.

**Pull request merged**
