### PR TITLE
[WIP] Updated release notes and vsixmanifest.

### PR DESCRIPTION
**Pull request by ashtonkj**
Tested on my local Visual Studio (though I had to build in Visual Studio as I don't have VS2013 on my machine so the FAKE build doesn't work. Does Appveyor run PRs?

### CODE REVIEW

**Comment by ashtonkj** [comment]
Ok. Just testing out the build artifact. If all goes well I will let you know.

**Comment by ashtonkj** [comment]
Curses. It doesn't work. I am looking into why.

**Comment by forki** [comment]
Would this break older vs? 

/cc @hmemcpy

**Comment by ashtonkj** [comment]
@forki it shouldn't. I am only changing the manifest. I am running a few more tests locally. Looks like I got the manifest wrong.

**Comment by ashtonkj** [comment]
Hmmm. Looks like AppVeyor doesn't build it properly for Vs2017. Builds and installs fine locally. I think I might have to wait for @hmemcpy to give me some pointers on how to get this to work.

**Comment by forki** [comment]
@hmemcpy is not really doing lot's of .NET anymore. So I'm afraid you need to ask someone else for help

**Comment by ashtonkj** [comment]
No worries. I'll dig around this weekend and try and sort it out. I will look at seeing what I can do about getting it running without breaking VS2013 (although I think this might be part of the problem).

**Comment by ashtonkj** [comment]
@forki, if @hmemcpy isn't doing much .NET any more, do you think it is worth me also looking at his other pull request?

**Comment by forki** [comment]
any progress?

**Comment by ashtonkj** [comment]
Some, but the appveyor build doesn't like it. I am busy looking at what might be missing to make appveyor happy..

**Comment by hmemcpy** [comment]
Sorry I haven't been active on this. I'm gonna try installing the latest VS to try it myself :)
I've been out of the loop, but as far as I remember, VS SDK no longer requires things to be installed, everything comes from nuget packages.
Must be a config issue. Anyway, I'll let you know :)

**Comment by hmemcpy** [comment]
Hmm, looks like lots has changed in the past 6 months... https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017

This may require having 2 separate vsix, I'm afraid, some new requirements that are probably not backwards-compatible. I'll keep digging 👀

**Comment by hmemcpy** [comment]
I'm tackling this as part of #133. There are a few changes to make it build properly. Still needs a FAKE fix (https://github.com/fsharp/FAKE/issues/1442)

**Comment by forki** [comment]
@ashtonkj  thanks for getting this started

**Pull request closed without merging**
