### PR TITLE
Make it compatible with Visual Studio 2012

### PR DESCRIPTION
**Pull request by mrinaldi**
We are referencing Visual Studio 2013's assemblies.

It won't work in a machine with VS 2012 only:

img_30102015_143820

Since we're not using any specific feature in VS 2013+, this PRs just changes the referenced assemblies back to VS 2012's.

### CODE REVIEW

**Comment by forki** [comment]
@hmemcpy could you please review this

**Comment by mrinaldi** [comment]
I've updated the PR to make it merge-able after PR #83.

@hmemcpy do you happen to have some time to review it? thanks.

**Comment by hmemcpy** [comment]
Sorry it took me a while to get here.
May I ask why are you on 2012?

The reason I initially targeted 2013+ was I wanted to use an API to create a custom item in the solution explorer, which was only available in 2013+.
We implemented this using the Graph API instead, which is available on older VS, however we might have to change this impl. in the future.
That's why I'm inclined not to accept this PR, unless there's a good reason to.

**Comment by mrinaldi** [comment]
It's not me, but part of my team actually.
We are in the process to migrate to 2015, but some ppl haven't done it yet.

Since Visual Studio Gallery lists it as supporting 2012 and it wasn't using any of the 2013+ API, I thought we should change it to reference the 2012 SDK.
However, if you're working on a feature that uses the 2013+ APIs that will be merged eventually, I agree this PR should not be accepted.

I think we should drop the support for 2012 in [source.extension.vsixmanifest](https://github.com/fsprojects/Paket.VisualStudio/blob/62d4953/src/Paket.VisualStudio/source.extension.vsixmanifest) though, since it's not supported anyway.

**Pull request closed without merging**
