### PR TITLE
Adding automatic restore

### PR DESCRIPTION
**Pull request by mrinaldi**
This PR restores automatically the packages before the build.

It shows a dialog while restoring
dialog

In case an error occurs, it'll report to the Error List
errorlist

It'll also write to the output window
output

And you can disable it if you want:
options

### CODE REVIEW

**Comment by forki** [comment]
WOOOT!

**Comment by hmemcpy** [comment]
Amazing! Thanks a lot! :+1:

**Comment by rojepp** [comment]
Nice! Please get rid of the dialog and show progress in regular build output instead.

**Comment by mrinaldi** [comment]
Why exactly do you want to get rid of the dialog?

Since the restore must be run before the build actually starts, it has no choice but to make VS unresponsive (at least I've found no other way).

That means even getting rid of the dialog, VS would still not accept any user input.

**Comment by rojepp** [comment]
Sorry, I misread this PR, I thought it was part of Paket itself, not VS.Paket. :) 
I always thought Paket did automatic restore through Paket.targets, just like NuGet does. I've clearly been using Fake too much. If so, why isn't this implemented in Paket.targets instead?

**Comment by forki** [comment]
Yes Paket.targets also allows restore. But only as part of the build

**Comment by rojepp** [comment]
So what does this PR do? My initial thought was that if you don't use fake with a `build.cmd` or `build.sh` that it would help for people using only VS?

**Comment by mrinaldi** [comment]
This PR restores the packages without relying on paket.targets.
Building on VS, it'll restore the packages.
Building on FAKE, you can call the restore before starting the build.

Why, you might ask. Because I had trouble with paket.targets.
Having a cpu with 8 threads and lots of projects in a solution, paket.targets randomly fails to acquire the lock to the packages folder when VS/MSBuild compiles projects in parallel.

Since now the restore is made sequentially, before the build starts, it won't have trouble locking.

**Comment by forki** [comment]
it would also be interesting to restore on VS project load

**Comment by rojepp** [comment]
Thanks for explaining.

**Pull request merged**
